### ISSUE TITLE
TypeError("QgsPolygon3DSymbol.setAltitudeBinding(): argument 1 has unexpected type 'int'")

### ISSUE THREAD

**Issue by pdinkins** [arthurRuf/3dcitybuilder#4]
```
appContext.user_parameters.building_height_method: {'title': 'Mode (the value that most repeats)', 'algorithm': 'native:zonalstatistics', 'method_id': 9}
building_height_method: 2
TypeError("QgsPolygon3DSymbol.setAltitudeBinding(): argument 1 has unexpected type 'int'")
Traceback (most recent call last):
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\citygen\generate_model\main.py", line 96, in start
    gis.generate_3d_model()
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\citygen\generate_model\gis\gis.py", line 285, in generate_3d_model
    load_layers_to_project()
  File "C:\Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\citygen\generate_model\gis\gis.py", line 220, in load_layers_to_project
    symbol.setAltitudeBinding(1)
TypeError: QgsPolygon3DSymbol.setAltitudeBinding(): argument 1 has unexpected type 'int'
```

Happens when trying to generate the model on Windows 10 with the sample Vienna dataset.

**Comment by justmejust2** [comment]
hope this fixed as soon as posiible. the plugin is ammazing if it did the job.
the problem is around building height i tried another selection from the dropdown list and now i am waiting for the result.
just go to Advance and try another input for Building height.
hope this help
